# Generated by Django 6.1 on 2026-08-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('kategori', models.CharField(choices=[('masyarakat', 'Kegiatan Masyarakat'), ('posyandu', 'Posyandu'), ('pemberdayaan', 'Pemberdayaan'), ('desa', 'Kegiatan Desa'), ('kkn', 'Program KKN'), ('lainnya', 'Lainnya')], default='lainnya', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='kegiatan/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_arsip', models.BooleanField(default=False, help_text='Centang jika kegiatan sudah selesai (arsip)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
