# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('kategori', models.CharField(choices=[('umkm', 'UMKM'), ('kesehatan', 'Kesehatan'), ('lingkungan', 'Lingkungan'), ('edukasi', 'Edukasi'), ('lainnya', 'Lainnya')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='program/thumbnail/')),
                ('latar_belakang', tinymce.models.HTMLField(blank=True)),
                ('permasalahan', tinymce.models.HTMLField(blank=True)),
                ('tujuan', tinymce.models.HTMLField(blank=True)),
                ('sasaran', models.TextField(blank=True)),
                ('pelaksanaan', tinymce.models.HTMLField(blank=True)),
                ('hasil', tinymce.models.HTMLField(blank=True)),
                ('dampak', tinymce.models.HTMLField(blank=True)),
                ('luaran', tinymce.models.HTMLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Pemberdayaan',
                'verbose_name_plural': 'Program Pemberdayaan',
                'ordering': ['kategori', 'urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='DokumentasiProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='program/dokumentasi/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('jenis', models.CharField(choices=[('before', 'Sebelum'), ('after', 'Sesudah'), ('proses', 'Proses'), ('umum', 'Umum')], default='umum', max_length=20)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi', to='program.program')),
            ],
            options={
                'verbose_name': 'Dokumentasi Program',
                'verbose_name_plural': 'Dokumentasi Program',
                'ordering': ['urutan'],
            },
        ),
    ]
