# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPotensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ikon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, contoh: bi-leaf', max_length=100)),
                ('deskripsi_singkat', models.TextField(blank=True)),
                ('foto_cover', models.ImageField(blank=True, null=True, upload_to='potensi/kategori/')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategori Potensi',
                'verbose_name_plural': 'Kategori Potensi',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='ItemPotensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', tinymce.models.HTMLField(help_text='Hanya isi dengan data yang sudah diverifikasi dari lapangan')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='potensi/items/')),
                ('sumber_data', models.CharField(blank=True, help_text='Sumber informasi data ini', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='potensi.kategoripotensi')),
            ],
            options={
                'verbose_name': 'Item Potensi',
                'verbose_name_plural': 'Item Potensi',
                'ordering': ['kategori', 'urutan', 'judul'],
            },
        ),
    ]
