# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('warna_label', models.CharField(default='success', help_text='Warna Bootstrap: success, primary, warning, info, danger, secondary', max_length=50)),
            ],
            options={
                'verbose_name': 'Kategori Artikel',
                'verbose_name_plural': 'Kategori Artikel',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artikel/thumbnail/')),
                ('penulis', models.CharField(blank=True, max_length=200)),
                ('tanggal_publish', models.DateField()),
                ('isi', tinymce.models.HTMLField()),
                ('ringkasan', models.TextField(blank=True, help_text='Ringkasan singkat untuk kartu artikel (maks 300 karakter)', max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Centang untuk ditampilkan di Home')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel', to='artikel.kategoriartikel')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-tanggal_publish'],
            },
        ),
    ]
