# Generated by Django 6.1 on 2026-08-12 08:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FasilitasDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('pendidikan', 'Pendidikan'), ('kesehatan', 'Kesehatan'), ('ibadah', 'Ibadah'), ('pemerintahan', 'Pemerintahan'), ('olahraga', 'Olahraga'), ('lainnya', 'Lainnya')], max_length=50)),
                ('dusun', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fasilitas Desa',
                'verbose_name_plural': 'Fasilitas Desa',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='ProfilDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(default='Sumberagung', max_length=200)),
                ('kecamatan', models.CharField(default='Weleri', max_length=200)),
                ('kabupaten', models.CharField(default='Kendal', max_length=200)),
                ('provinsi', models.CharField(default='Jawa Tengah', max_length=200)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('luas_wilayah', models.CharField(blank=True, help_text='Contoh: 3,5 km²', max_length=100)),
                ('jumlah_dusun', models.PositiveIntegerField(blank=True, null=True)),
                ('koordinat_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('koordinat_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('deskripsi_singkat', models.TextField(blank=True, help_text='Deskripsi singkat untuk ditampilkan di Hero/Sekilas')),
                ('sejarah', tinymce.models.HTMLField(blank=True, help_text='Isi hanya jika data sejarah sudah divalidasi perangkat desa')),
                ('kondisi_wilayah', tinymce.models.HTMLField(blank=True)),
                ('demografi', tinymce.models.HTMLField(blank=True, help_text='Tampilkan hanya data yang diizinkan untuk dipublikasikan')),
                ('foto_header', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('maps_embed_url', models.URLField(blank=True, help_text='URL embed Google Maps untuk desa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Desa',
                'verbose_name_plural': 'Profil Desa',
            },
        ),
    ]
