# Generated by Django 4.2.30 on 2026-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profildesa',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video profil (disarankan format MP4, maks 30MB)', null=True, upload_to='profil/video/'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='video_youtube_url',
            field=models.URLField(blank=True, help_text='ATAU masukkan URL embed YouTube jika file video terlalu besar (akan diprioritaskan)'),
        ),
    ]
