# Generated by Django 4.2.30 on 2026-08-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profildesa_video_file_profildesa_video_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profildesa',
            name='video_deskripsi',
            field=models.TextField(blank=True, help_text='Deskripsi singkat tentang video profil yang tampil di halaman video'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='video_produksi',
            field=models.CharField(blank=True, help_text='Nama tim/pihak produksi video (misal: Tim KKN Undip 2026)', max_length=200),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='video_tahun',
            field=models.CharField(blank=True, help_text='Tahun produksi video (misal: 2026)', max_length=4),
        ),
    ]
