# Generated by Django 4.2.30 on 2026-08-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_profildesa_video_deskripsi_profildesa_video_produksi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profildesa',
            name='video_durasi',
            field=models.CharField(blank=True, help_text='Durasi video (misal: 5 menit 30 detik)', max_length=20),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='video_highlight',
            field=models.TextField(blank=True, help_text='Poin-poin highlight video, pisahkan dengan baris baru (Enter). Contoh: Potensi pertanian\nBudaya lokal\nKehidupan masyarakat'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='video_link',
            field=models.URLField(blank=True, help_text='Link video publik untuk dibagikan (YouTube, Google Drive, dll)'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='video_sinopsis',
            field=models.TextField(blank=True, help_text='Sinopsis/ringkasan isi video profil (paragraf lebih panjang)'),
        ),
    ]
