# Generated by Django 4.2.30 on 2026-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_profildesa_video_durasi_profildesa_video_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profildesa',
            name='sosmed_facebook',
            field=models.URLField(blank=True, help_text='URL halaman Facebook'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='sosmed_instagram',
            field=models.URLField(blank=True, help_text='URL profil Instagram (misal: https://instagram.com/desasumberagung)'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='sosmed_tiktok',
            field=models.URLField(blank=True, help_text='URL profil TikTok'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='sosmed_whatsapp',
            field=models.CharField(blank=True, help_text='Nomor WhatsApp (format: 628xxxxxxxx)', max_length=20),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='sosmed_youtube',
            field=models.URLField(blank=True, help_text='URL channel YouTube'),
        ),
    ]
