# Generated by Django 4.2.30 on 2026-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontribusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama pengirim (boleh nama samaran)', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email opsional, untuk kami menghubungi balik', max_length=254)),
                ('jenis', models.CharField(choices=[('cerita', 'Cerita / Pengalaman'), ('masukan', 'Masukan / Saran'), ('koreksi', 'Koreksi Informasi'), ('lainnya', 'Lainnya')], default='masukan', max_length=20)),
                ('pesan', models.TextField(help_text='Tulis cerita atau masukan Anda')),
                ('is_approved', models.BooleanField(default=False, help_text='Centang untuk menampilkan ke publik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontribusi',
                'verbose_name_plural': 'Kontribusi Masyarakat',
                'ordering': ['-created_at'],
            },
        ),
    ]
