# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=300)),
                ('tanggal', models.DateField()),
                ('dusun', models.CharField(max_length=100)),
                ('jumlah_peserta', models.PositiveIntegerField()),
                ('rentang_usia', models.CharField(blank=True, help_text='Contoh: 45–80 tahun', max_length=100)),
                ('catatan', models.TextField(blank=True, help_text='Catatan umum kegiatan, bukan data individual')),
                ('disclaimer_text', models.TextField(default='Data pada bagian ini merupakan ringkasan hasil kegiatan/skrining peserta program dan tidak merepresentasikan kondisi kesehatan seluruh masyarakat Desa Sumberagung. Informasi ditampilkan untuk tujuan dokumentasi dan edukasi, bukan sebagai diagnosis medis.', help_text='Disclaimer wajib tampil di halaman Insight Kesehatan')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Kesehatan',
                'verbose_name_plural': 'Event Kesehatan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='DataAgregatKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indikator', models.CharField(choices=[('tekanan_darah', 'Tekanan Darah'), ('gula_darah', 'Gula Darah'), ('kolesterol', 'Kolesterol'), ('asam_urat', 'Asam Urat'), ('berat_badan', 'Berat Badan / IMT'), ('lainnya', 'Lainnya')], max_length=50)),
                ('label_nilai', models.CharField(help_text='Contoh: Normal, Pra-Hipertensi, Hipertensi Stage 1', max_length=100)),
                ('jumlah', models.PositiveIntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_agregat', to='insight.eventkesehatan')),
            ],
            options={
                'verbose_name': 'Data Agregat Kesehatan',
                'verbose_name_plural': 'Data Agregat Kesehatan',
                'ordering': ['event', 'indikator'],
            },
        ),
    ]
