# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriUMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kategori UMKM',
                'verbose_name_plural': 'Kategori UMKM',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('nama_pemilik', models.CharField(blank=True, max_length=200)),
                ('dusun', models.CharField(blank=True, max_length=100)),
                ('deskripsi', tinymce.models.HTMLField(blank=True)),
                ('produk_unggulan', models.TextField(blank=True, help_text='Produk-produk unggulan, pisahkan dengan koma')),
                ('foto_utama', models.ImageField(blank=True, null=True, upload_to='umkm/foto/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='umkm/logo/')),
                ('izin_publikasi_kontak', models.BooleanField(default=False, help_text='Centang jika pemilik sudah memberikan izin publikasi kontak')),
                ('kontak_wa', models.CharField(blank=True, help_text='Nomor WhatsApp tanpa awalan + atau 0', max_length=20)),
                ('instagram', models.CharField(blank=True, help_text='Username Instagram tanpa @', max_length=100)),
                ('marketplace_url', models.URLField(blank=True, help_text='URL toko di marketplace (Shopee, Tokopedia, dll)')),
                ('google_maps_url', models.URLField(blank=True)),
                ('qris_image', models.ImageField(blank=True, null=True, upload_to='umkm/qris/')),
                ('hasil_pendampingan', tinymce.models.HTMLField(blank=True, help_text='Ceritakan hasil pendampingan: branding, kemasan, QRIS, dll')),
                ('is_published', models.BooleanField(default=False, help_text='Centang untuk menampilkan di website')),
                ('is_featured', models.BooleanField(default=False, help_text='Centang untuk ditampilkan di halaman Home')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umkm_list', to='umkm.kategoriumkm')),
            ],
            options={
                'verbose_name': 'UMKM Mitra',
                'verbose_name_plural': 'UMKM Mitra',
                'ordering': ['nama_usaha'],
            },
        ),
        migrations.CreateModel(
            name='PendampinganBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('branding', 'Branding/Logo'), ('kemasan', 'Kemasan'), ('label', 'Label Produk'), ('qris', 'QRIS'), ('digital', 'Digital Marketing'), ('katalog', 'Katalog'), ('lainnya', 'Lainnya')], max_length=50)),
                ('foto_sebelum', models.ImageField(blank=True, null=True, upload_to='umkm/before/')),
                ('foto_sesudah', models.ImageField(blank=True, null=True, upload_to='umkm/after/')),
                ('keterangan', models.TextField(blank=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendampingan', to='umkm.umkm')),
            ],
            options={
                'verbose_name': 'Pendampingan Before-After',
                'verbose_name_plural': 'Pendampingan Before-After',
            },
        ),
        migrations.CreateModel(
            name='FotoUMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='umkm/galeri/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_galeri', to='umkm.umkm')),
            ],
            options={
                'verbose_name': 'Foto UMKM',
                'verbose_name_plural': 'Foto UMKM',
                'ordering': ['urutan'],
            },
        ),
    ]
