# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ikon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons', max_length=100)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategori Edukasi',
                'verbose_name_plural': 'Kategori Edukasi',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='ItemEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('pembuat', models.CharField(blank=True, help_text='Nama pembuat/tim yang membuat materi', max_length=200)),
                ('program_asal', models.CharField(blank=True, help_text='Program KKN asal materi ini', max_length=200)),
                ('file_upload', models.FileField(upload_to='edukasi/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='edukasi/thumbnail/')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jumlah_download', models.PositiveIntegerField(default=0, editable=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='edukasi.kategoriedukasi')),
            ],
            options={
                'verbose_name': 'Item Edukasi',
                'verbose_name_plural': 'Item Edukasi',
                'ordering': ['-tanggal', 'judul'],
            },
        ),
    ]
