# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategori Galeri',
                'verbose_name_plural': 'Kategori Galeri',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='ItemGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('judul', models.CharField(blank=True, max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Centang untuk tampil di halaman Home')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='galeri.kategorigaleri')),
            ],
            options={
                'verbose_name': 'Item Galeri',
                'verbose_name_plural': 'Item Galeri',
                'ordering': ['-created_at', 'urutan'],
            },
        ),
    ]
